#7 - [FA] Sign Up - Petar
ChidimmaOfodum/deskeando pull request #16
Opened 2023-12-08 13:36 UTC by Nikolov87

## Naming Rules
Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description
Write a summary of your change. Explain why you have made it.
Creating and sailing Sign Up form

## Related to
#7

## Checklist:
- [ x ] My code follows the style guidelines of this project
- [ x ] I have carefully reviewed my own code
- [ x ] I have commented my code
- [ x ] I have updated any documentation

2023-12-08 14:06 UTC, Johng117 approved these changes
Good Job Petar.

2023-12-08 14:36 UTC, ChidimmaOfodum requested changes

2023-12-08 14:36 UTC, ChidimmaOfodum commented on client/src/Pages/Signup/SignupForm.js
> +		// Perform your signup logic here using the state variables
The signup data should be sent to the backend with a post request. The logic is missing.

2023-12-08 14:36 UTC, ChidimmaOfodum commented on client/src/Pages/Signup/SignupForm.js
> +		SelectDepartment === "admin" ? "/admin-dashboard" : "/staff-dashboard";
Staff in HR department are admins

2023-12-08 14:36 UTC, ChidimmaOfodum commented on client/src/Pages/Signup/SignupForm.js
> +							<option value="staff" href="#">
The department data will be fetched from the api and displayed here

2023-12-08 14:37 UTC, ChidimmaOfodum commented
Thank you Petar. Also remember to pull the recent changes from the dev branch before making a pull request

2023-12-09 10:51 UTC, merged

2023-12-10 06:04 UTC, Nikolov87 commented on client/src/Pages/Signup/SignupForm.js
> +							<option value="staff" href="#">
Thank you Chidimma, this is fixed :)